In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.read_csv("../data/processed/cleaned_sales_data.csv")
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75995,2024-01-30,S005,P0016,Toys,North,233,63,0,29.80,5,Snowy,0,32.23,Winter,0,64
75996,2024-01-30,S005,P0017,Toys,North,137,115,141,42.92,5,Snowy,0,40.73,Winter,0,137
75997,2024-01-30,S005,P0018,Clothing,North,197,44,0,17.81,10,Snowy,0,19.41,Winter,0,68
75998,2024-01-30,S005,P0019,Furniture,North,125,58,0,151.72,0,Snowy,0,143.71,Winter,0,84
75999,2024-01-30,S005,P0020,Toys,North,126,63,59,25.78,10,Snowy,0,29.32,Winter,0,73

In [40]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [41]:
df.shape

(76000, 16)

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  str
 1   Store ID            76000 non-null  str
 2   Product ID          76000 non-null  str
 3   Category            76000 non-null  str
 4   Region              76000 non-null  str
 5   Inventory Level     76000 non-null  int64
 6   Units Sold          76000 non-null  int64
 7   Units Ordered       76000 non-null  int64
 8   Price               76000 non-null  float64
 9   Discount            76000 non-null  int64
 10  Weather Condition   76000 non-null  str
 11  Promotion           76000 non-null  int64
 12  Competitor Pricing  76000 non-null  float64
 13  Seasonality         76000 non-null  str
 14  Epidemic            76000 non-null  int64
 15  Demand              76000 non-null  int64
dtypes: float64(2), int64(7), str(7)
memory usage: 12.4 MB

In [43]:
df["Date"] = pd.to_datetime(df["Date"])

In [44]:
df["Year"] = df["Date"].dt.year

In [45]:
df["Month"] = df["Date"].dt.month

In [46]:
df["Day"] = df["Date"].dt.day

In [47]:
df["DayOfWeek"] = df["Date"].dt.dayofweek

In [48]:
df["Quarter"] = df["Date"].dt.quarter

In [49]:
df[
    [
        "Date",
        "Year",
        "Month",
        "Day",
        "DayOfWeek",
        "Quarter"
    ]
].head()

        Date  Year  Month  Day  DayOfWeek  Quarter
0 2022-01-01  2022      1    1          5        1
1 2022-01-01  2022      1    1          5        1
2 2022-01-01  2022      1    1          5        1
3 2022-01-01  2022      1    1          5        1
4 2022-01-01  2022      1    1          5        1

In [50]:
df["Price_Difference"] = (
    df["Price"] - df["Competitor Pricing"]
)

In [51]:
df["Price_Ratio"] = (
    df["Price"] / df["Competitor Pricing"]
)

In [52]:
df["Price_Difference_Percent"] = (
    (df["Price"] - df["Competitor Pricing"])
    / df["Competitor Pricing"]
) * 100

In [53]:
df["Discount"].describe()

count    76000.000000
mean         9.087039
std          7.475781
min          0.000000
25%          5.000000
50%         10.000000
75%         10.000000
max         25.000000
Name: Discount, dtype: float64

In [54]:
df["Effective_Price"] = df["Price"] * (1 - df["Discount"] / 100)

In [55]:
df["Stock_Status"] = np.where(
    df["Inventory Level"] == 0,
    "Out_of_Stock",
    "In_Stock"
)

In [56]:
df["Inventory_to_Order_Ratio"] = (
    df["Inventory Level"] /
    (df["Units Ordered"] + 1)
)

In [57]:
categorical_columns = [
    "Category",
    "Region",
    "Weather Condition",
    "Seasonality",
    "Promotion",
    "Epidemic",
    "Stock_Status"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].unique())

Category
<ArrowStringArray>
['Electronics', 'Clothing', 'Groceries', 'Toys', 'Furniture']
Length: 5, dtype: str

Region
<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

Weather Condition
<ArrowStringArray>
['Snowy', 'Cloudy', 'Sunny', 'Rainy']
Length: 4, dtype: str

Seasonality
<ArrowStringArray>
['Winter', 'Spring', 'Summer', 'Autumn']
Length: 4, dtype: str

Promotion
[0 1]

Epidemic
[0 1]

Stock_Status
<ArrowStringArray>
['In_Stock', 'Out_of_Stock']
Length: 2, dtype: str

In [62]:
new_features = [
    "Year",
    "Month",
    "Day",
    "DayOfWeek",
    "Quarter",
    "Price_Difference",
    "Price_Ratio",
    "Price_Difference_Percent",
    "Effective_Price",
    "Stock_Status",
    "Inventory_to_Order_Ratio"
]

df[new_features].head()

,Year,Month,Day,DayOfWeek,Quarter,Price_Difference,Price_Ratio,Price_Difference_Percent,Effective_Price,Stock_Status,Inventory_to_Order_Ratio
0,2022,1,1,5,1,-13.01,0.848244,-15.175551,69.084,In_Stock,0.770751
1,2022,1,1,5,1,-11.86,0.871115,-12.888502,68.136,In_Stock,0.468000
2,2022,1,1,5,1,2.86,1.047603,4.760320,56.646,In_Stock,0.402936
3,2022,1,1,5,1,2.44,1.028642,2.864186,78.867,In_Stock,1.349515
4,2022,1,1,5,1,2.78,1.053845,5.384466,54.410,In_Stock,0.558824

In [63]:
np.isinf(df.select_dtypes(include=np.number)).sum()

Inventory Level             0
Units Sold                  0
Units Ordered               0
Price                       0
Discount                    0
Promotion                   0
Competitor Pricing          0
Epidemic                    0
Demand                      0
Year                        0
Month                       0
Day                         0
DayOfWeek                   0
Quarter                     0
Price_Difference            0
Price_Ratio                 0
Price_Difference_Percent    0
Effective_Price             0
Inventory_to_Order_Ratio    0
dtype: int64

In [64]:
df.isnull().sum()

Date                        0
Store ID                    0
Product ID                  0
Category                    0
Region                      0
Inventory Level             0
Units Sold                  0
Units Ordered               0
Price                       0
Discount                    0
Weather Condition           0
Promotion                   0
Competitor Pricing          0
Seasonality                 0
Epidemic                    0
Demand                      0
Year                        0
Month                       0
Day                         0
DayOfWeek                   0
Quarter                     0
Price_Difference            0
Price_Ratio                 0
Price_Difference_Percent    0
Effective_Price             0
Stock_Status                0
Inventory_to_Order_Ratio    0
dtype: int64

In [65]:
df.shape

(76000, 27)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      76000 non-null  datetime64[us]
 1   Store ID                  76000 non-null  str
 2   Product ID                76000 non-null  str
 3   Category                  76000 non-null  str
 4   Region                    76000 non-null  str
 5   Inventory Level           76000 non-null  int64
 6   Units Sold                76000 non-null  int64
 7   Units Ordered             76000 non-null  int64
 8   Price                     76000 non-null  float64
 9   Discount                  76000 non-null  int64
 10  Weather Condition         76000 non-null  str
 11  Promotion                 76000 non-null  int64
 12  Competitor Pricing        76000 non-null  float64
 13  Seasonality               76000 non-null  str
 14  Epidemic                  76000 non-null  int64
 15  Demand                    76000 non-null  int64
 16  Year                      76000 non-null  int32
 17  Month                     76000 non-null  int32
 18  Day                       76000 non-null  int32
 19  DayOfWeek                 76000 non-null  int32
 20  Quarter                   76000 non-null  int32
 21  Price_Difference          76000 non-null  float64
 22  Price_Ratio               76000 non-null  float64
 23  Price_Difference_Percent  76000 non-null  float64
 24  Effective_Price           76000 non-null  float64
 25  Stock_Status              76000 non-null  str
 26  Inventory_to_Order_Ratio  76000 non-null  float64
dtypes: datetime64[us](1), float64(7), int32(5), int64(7), str(7)
memory usage: 17.2 MB

In [67]:
df["Date"]

0       2022-01-01
1       2022-01-01
2       2022-01-01
3       2022-01-01
4       2022-01-01
           ...
75995   2024-01-30
75996   2024-01-30
75997   2024-01-30
75998   2024-01-30
75999   2024-01-30
Name: Date, Length: 76000, dtype: datetime64[us]

In [68]:
df = df.sort_values("Date").reset_index(drop=True)

In [69]:
df["Date"].is_monotonic_increasing

True

In [70]:
df.to_csv(
    "../data/processed/feature_engineered_sales_data.csv",
    index=False
)

In [71]:
df.columns.tolist()

['Date',
 'Store ID',
 'Product ID',
 'Category',
 'Region',
 'Inventory Level',
 'Units Sold',
 'Units Ordered',
 'Price',
 'Discount',
 'Weather Condition',
 'Promotion',
 'Competitor Pricing',
 'Seasonality',
 'Epidemic',
 'Demand',
 'Year',
 'Month',
 'Day',
 'DayOfWeek',
 'Quarter',
 'Price_Difference',
 'Price_Ratio',
 'Price_Difference_Percent',
 'Effective_Price',
 'Stock_Status',
 'Inventory_to_Order_Ratio']